In [1]:
a=10
a


10

In [3]:
"sahithi"


'sahithi'

In [4]:
!pip install numpy


In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [8]:
b= np.array([1,2,3,4,'a'])
b

array(['1', '2', '3', '4', 'a'], dtype='<U11')

In [9]:
c=np.array(10)
d=np.array([1,2,3,4])
e=np.array([[1,2,3],[4,5,6]])
f=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print('c dimension:',c.ndim)
print("d dim:",d.ndim)
print("e dim:",e.ndim)
print("f dim:",f.ndim)

c dimension: 0
d dim: 1
e dim: 2
f dim: 3


In [10]:
print("shape of c:",c.shape)
print("shape of d:",d.shape)
print("shape of e:",e.shape)
print("shape of f:",f.shape)

shape of c: ()
shape of d: (4,)
shape of e: (2, 3)
shape of f: (1, 3, 3)


In [11]:
print(d.dtype)

int32


In [12]:
print(type(d))

<class 'numpy.ndarray'>


In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.eye(3,dtype = float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
#defaultly it will give output in float format
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
#it also gives output in float format
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [23]:
#it gives output in int format
np.full((3,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [24]:
x=[1,2,3,4,5,6,7]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [26]:
x = np.arange(1,17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [27]:
print(x.shape)
print(x.ndim)

(16,)
1


In [29]:
n= x.reshape(8,2)
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [33]:
m=n.reshape((2,8),order='c')
m

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [32]:
s=n.reshape((4,4))
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
p=s.reshape((2,4,2),order='c')

In [37]:
p

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [38]:
r=p.ravel()
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [39]:
m.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [40]:
p.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [42]:
x1=np.array([1,2,3,4,5,6,7])
x2=x1
print(x2)

[1 2 3 4 5 6 7]


In [43]:
x1[0]=100
x2

array([100,   2,   3,   4,   5,   6,   7])

In [44]:
x3=x1.view()
x3

array([100,   2,   3,   4,   5,   6,   7])

In [45]:
x3[0]=200
print(x1,x2,x3)


[200   2   3   4   5   6   7] [200   2   3   4   5   6   7] [200   2   3   4   5   6   7]


In [49]:
id(x1)
id(x2)
id(x3)

2411600322160

In [50]:
np.shares_memory(x1,x3)

True

In [52]:
p.transpose()

array([[[ 1,  9],
        [ 3, 11],
        [ 5, 13],
        [ 7, 15]],

       [[ 2, 10],
        [ 4, 12],
        [ 6, 14],
        [ 8, 16]]])

In [54]:
s.transpose()

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [56]:
np.vstack((x1,x3))

array([[200,   2,   3,   4,   5,   6,   7],
       [200,   2,   3,   4,   5,   6,   7]])

In [57]:
np.hstack((x1,x3))

array([200,   2,   3,   4,   5,   6,   7, 200,   2,   3,   4,   5,   6,
         7])

In [58]:
np.insert(x1,3,x3)

array([200,   2,   3, 200,   2,   3,   4,   5,   6,   7,   4,   5,   6,
         7])

In [59]:
np.delete(x1,0)

array([2, 3, 4, 5, 6, 7])

In [60]:
x1


array([200,   2,   3,   4,   5,   6,   7])

In [61]:
# where fun gives us index of actual values and it allows duplicate values
np.where(x1%2==0)

(array([0, 1, 3, 5], dtype=int64),)

In [62]:
np.where(x1>5,x1,0)

array([200,   0,   0,   0,   0,   6,   7])